import {useEffect,useState} from 'react'
import type {FormEvent,ReactNode} from 'react'
import type {DashboardItem} from './dashboard'
import {getDashboard} from './dashboard'
import type {Animal,AnimalInput,Treatment,Administration,MedicalEvent,Vaccination,Deworming,MedicalDocument} from './api'
import {getAnimals,getTreatments,getAdministrations,generateAdministrations,administer,setAdministrationStatus,createAnimal,updateAnimal,getMedicalEvents,createMedicalEvent,getVaccinations,createVaccination,getDewormings,createDeworming,getDocuments,createDocument,uploadDocument,createTask,completeTask,skipTask,getAuditLogs,getUsers,deactivateUser,reactivateUser,createUser,getCurrentUser,changeMyPassword,resetUserPassword,updateUser} from './api'

const today=()=>new Date().toISOString().slice(0,10)
const blankAnimal=():AnimalInput=>({name:'',animalType:'DOG',sex:'UNKNOWN',dateOfBirth:'',weightKg:undefined,microchipNumber:'',intakeDate:today(),rescueSource:'',location:'',status:'ACTIVE',notes:'',photoUrl:''})

export default function App(){
 const [authenticated,setAuthenticated]=useState(!!localStorage.getItem('shelterAuth'))
 useEffect(()=>{const h=()=>setAuthenticated(false);window.addEventListener('shelter-auth-required',h);return()=>window.removeEventListener('shelter-auth-required',h)},[])
 return authenticated?<ShelterApp onLogout={()=>{localStorage.removeItem('shelterAuth');setAuthenticated(false)}}/>:<Login onLogin={()=>setAuthenticated(true)}/>
}
function Login({onLogin}:{onLogin:()=>void}){
 const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[error,setError]=useState('')
 async function submit(e:FormEvent){e.preventDefault();const token=btoa(username+':'+password);const r=await fetch('/api/animals',{headers:{Authorization:'Basic '+token}});if(!r.ok){setError('Invalid username or password');return}localStorage.setItem('shelterAuth',token);onLogin()}
 return <main className="login-shell"><form className="login-card" onSubmit={submit}><p className="eyebrow">SHELTER MANAGEMENT</p><h1>Sign in</h1><p className="muted">Access the animal care system.</p><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" autoComplete="username"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password" autoComplete="current-password"/>{error&&<div className="inline-error">{error}</div>}<button className="primary" type="submit">Sign in</button></form></main>
}
function ShelterApp({onLogout}:{onLogout:()=>void}){
 const [role,setRole]=useState('VIEWER'),[username,setUsername]=useState('')
 useEffect(()=>{getCurrentUser().then(u=>{setRole(u.role);setUsername(u.username)}).catch(()=>setRole('VIEWER'))},[])
 const isAdmin=role==='ADMIN'
 const [view,setView]=useState<'dashboard'|'animals'|'backups'|'audit'|'users'>('dashboard')
 if(view==='dashboard')return <Dashboard isAdmin={isAdmin} onOpenAnimals={()=>setView('animals')} onOpenBackups={()=>setView('backups')} onOpenAudit={()=>setView('audit')} onOpenUsers={()=>setView('users')} onLogout={onLogout}/>
 if(view==='backups'&&!isAdmin)return <Dashboard isAdmin={isAdmin} onOpenAnimals={()=>setView('animals')} onOpenBackups={()=>setView('backups')} onOpenAudit={()=>setView('audit')} onOpenUsers={()=>setView('users')} onLogout={onLogout}/>
 if(view==='backups')return <Backups onBack={()=>setView('dashboard')} onLogout={onLogout}/>
 if(view==='users'&&!isAdmin)return <Dashboard isAdmin={isAdmin} onOpenAnimals={()=>setView('animals')} onOpenBackups={()=>setView('backups')} onOpenAudit={()=>setView('audit')} onOpenUsers={()=>setView('users')} onLogout={onLogout}/>
 if(view==='users')return <Users currentUsername={username} onBack={()=>setView('dashboard')} onLogout={onLogout}/>
 if(view==='audit'&&!isAdmin)return <Dashboard isAdmin={isAdmin} onOpenAnimals={()=>setView('animals')} onOpenBackups={()=>setView('backups')} onOpenAudit={()=>setView('audit')} onOpenUsers={()=>setView('users')} onLogout={onLogout}/>
 if(view==='audit')return <Audit onBack={()=>setView('dashboard')} onLogout={onLogout}/>
 return <Animals onBack={()=>setView('dashboard')} onLogout={onLogout}/>
}
function Backups({onBack,onLogout}:{onBack:()=>void;onLogout:()=>void}){
 const [items,setItems]=useState<import('./api').BackupInfo[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
 async function load(){try{setItems(await import('./api').then(x=>x.getBackups()));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load backups')}}
 useEffect(()=>{load()},[])
 async function verify(name:string){setBusy(name);setMessage('');try{const r=await import('./api').then(x=>x.verifyBackup(name));setMessage(r.message)}catch(e){setError(e instanceof Error?e.message:'Could not verify backup')}finally{setBusy('')}}
 const size=(n:number)=>n<1024*1024?(n/1024).toFixed(1)+' KB':(n/1024/1024).toFixed(1)+' MB'
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">ADMINISTRATION</p><h1>Backups</h1><p className="muted">Local backup catalog and integrity verification</p></div><div className="top-actions"><button className="secondary" onClick={onBack}>Dashboard</button><button className="secondary" onClick={onLogout}>Sign out</button></div></header>
 {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
 <section className="panel"><div className="section-head"><div><p className="eyebrow">BACKUP CATALOG</p><h2>{items.length} backups</h2></div><button className="secondary" onClick={load}>Refresh</button></div>
 {items.length===0?<p className="muted">No backups are available in the configured backup folder.</p>:<div className="backup-list">{items.map(x=><div className="backup-item" key={x.name}><div><strong>{x.name}</strong><span>{new Date(x.createdAt).toLocaleString()} · DB {size(x.databaseBytes)} · Documents {size(x.documentsBytes)}</span></div><div className="actions"><span className={x.checksumAvailable?'status status-administered':'status status-missed'}>{x.checksumAvailable?'CHECKSUM':'NO CHECKSUM'}</span><button className="secondary small" disabled={busy===x.name} onClick={()=>verify(x.name)}>{busy===x.name?'Verifying…':'Verify'}</button></div></div>)}</div>}
 </section>
 <section className="panel"><p className="eyebrow">RESTORE</p><h2>Restore on a replacement computer</h2><p className="muted">Select and verify a backup before using the local restore procedure. Database restore remains a protected local operation and is not exposed as a browser button.</p></section>
 </main>
}
function ChangePasswordForm({onCancel,onChanged}:{onCancel:()=>void;onChanged:()=>void}){
 const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(){if(newPassword.length<12){setError('New password must be at least 12 characters');return}if(newPassword!==confirmPassword){setError('New passwords do not match');return}setBusy(true);setError('');try{await changeMyPassword(currentPassword,newPassword);localStorage.removeItem('shelterAuth');onChanged()}catch(e){setError(e instanceof Error?e.message:'Could not change password')}finally{setBusy(false)}}
 return <FormShell eyebrow="ACCOUNT SECURITY" title="Change password" onCancel={onCancel}><div className="form-grid"><label className="span-2">Current password *<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password"/></label><label>New password *<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password"/></label><label>Confirm new password *<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password"/></label></div><p className="muted">Minimum 12 characters. After changing the password you will be signed out and must sign in again.</p>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Changing…':'Change password'}</button></FormShell>
}
function Dashboard({isAdmin,onOpenAnimals,onOpenBackups,onOpenAudit,onOpenUsers,onLogout}:{isAdmin:boolean;onOpenAnimals:()=>void;onOpenBackups:()=>void;onOpenAudit:()=>void;onOpenUsers:()=>void;onLogout:()=>void}) {
 const [data,setData]=useState<{items:DashboardItem[];overdue:number;remaining:number;administered:number;overdueTasks:number;remainingTasks:number;taskItems:any[]}|null>(null)
 const [error,setError]=useState('')
 const [showTask,setShowTask]=useState(false)
 const [showPassword,setShowPassword]=useState(false)

 async function load() {
  try { setData(await getDashboard()); setError('') }
  catch(e) { setError(e instanceof Error?e.message:'Could not load dashboard') }
 }

 useEffect(()=>{ load(); const t=setInterval(load,60000); return()=>clearInterval(t) },[])
 const pending=data?.items.filter(x=>x.status==='SCHEDULED')||[]
 const overdue=pending.filter(x=>new Date(x.scheduledAt)<new Date())

 return <main className="shell">
  <header className="topbar">
   <div><p className="eyebrow">SHELTER MANAGEMENT</p><h1>Today</h1><p className="muted">Operational care dashboard</p></div>
   <div className="top-actions"><button className="secondary" onClick={onOpenAnimals}>Animals</button><button className="secondary" onClick={()=>setShowPassword(true)}>Change password</button>{isAdmin&&<><button className="secondary" onClick={onOpenBackups}>Backups</button><button className="secondary" onClick={onOpenAudit}>Audit log</button><button className="secondary" onClick={onOpenUsers}>Users</button></>}<button className="secondary" onClick={onLogout}>Sign out</button></div>
  </header>
  {error&&<div className="error">{error}</div>}
  <section className="dashboard-stats"><Stat label="Overdue" value={data?.overdue??'—'} danger/><Stat label="Remaining" value={data?.remaining??'—'}/><Stat label="Administered" value={data?.administered??'—'}/></section>
  <section className="panel dashboard-panel">
   <div className="section-head"><div><p className="eyebrow">ACTION QUEUE</p><h2>{overdue.length?'Overdue administrations':'Upcoming administrations'}</h2></div><span className="muted">{overdue.length?'Needs attention':'Today'}</span></div>
   {(overdue.length?overdue:pending).length===0?<p className="muted">No scheduled administrations for today.</p>:<div className="dashboard-list">{(overdue.length?overdue:pending).slice(0,20).map(x=><div className="dashboard-item" key={x.id}><div><strong>{x.animalName}</strong><span>{x.medication} · {x.dose} · {x.route}</span></div><div className="dashboard-time">{new Date(x.scheduledAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{overdue.includes(x)&&<span className="overdue-badge">OVERDUE</span>}</div></div>)}</div>}
  </section>
  <section className="panel dashboard-panel">
   <div className="section-head"><div><p className="eyebrow">TASKS & REMINDERS</p><h2>Open tasks</h2></div><div className="section-head-actions"><span className="muted">{(data?.taskItems||[]).length}</span><button className="primary small" onClick={()=>setShowTask(true)}>+ New task</button></div></div>
   {(data?.taskItems||[]).length===0?<p className="muted">No open tasks.</p>:<div className="dashboard-list">{(data?.taskItems||[]).slice(0,20).map(x=><div className="dashboard-item" key={x.id}><div><strong>{x.animalName||'Shelter task'}</strong><span>{x.title} · {x.priority}</span></div><div className="task-actions"><span className="dashboard-time">{new Date(x.dueAt).toLocaleString()}</span><button className="primary small" onClick={async()=>{await completeTask(x.id);load()}}>Complete</button><button className="secondary small" onClick={async()=>{await skipTask(x.id);load()}}>Skip</button></div></div>)}</div>}
  </section>
  <section className="panel dashboard-panel">
   <div className="section-head"><div><p className="eyebrow">TODAY</p><h2>Administration timeline</h2></div></div>
   <div className="dashboard-list">{(data?.items||[]).slice(0,30).map(x=><div className="dashboard-item" key={x.id}><div><strong>{x.animalName}</strong><span>{x.medication} · {x.dose}</span></div><span className={'status status-'+x.status.toLowerCase()}>{x.status}</span></div>)}</div>
  </section>
  {showTask&&<TaskForm onCancel={()=>setShowTask(false)} onSaved={()=>{setShowTask(false);load()}}/>}
  {showPassword&&<ChangePasswordForm onCancel={()=>setShowPassword(false)} onChanged={onLogout}/>}\n </main>
}
function Users({currentUsername,onBack,onLogout}:{currentUsername:string;onBack:()=>void;onLogout:()=>void}){
 const [items,setItems]=useState<import('./api').ShelterUser[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[showCreate,setShowCreate]=useState(false),[resetUser,setResetUser]=useState<import('./api').ShelterUser|null>(null),[editUser,setEditUser]=useState<import('./api').ShelterUser|null>(null)
 async function load(){try{setItems(await getUsers());setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load users')}}
 useEffect(()=>{load()},[])
 async function toggle(u:import('./api').ShelterUser){setBusy(u.id);setError('');try{const updated=u.active?await deactivateUser(u.id):await reactivateUser(u.id);setItems(xs=>xs.map(x=>x.id===updated.id?updated:x))}catch(e){setError(e instanceof Error?e.message:'Could not update user')}finally{setBusy('')}}
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">ADMINISTRATION</p><h1>Users</h1><p className="muted">Manage shelter system accounts and access status</p></div><div className="top-actions"><button className="secondary" onClick={onBack}>Dashboard</button><button className="secondary" onClick={onLogout}>Sign out</button></div></header>
 {error&&<div className="error">{error}</div>}
 <section className="panel"><div className="section-head"><div><p className="eyebrow">USER ACCOUNTS</p><h2>{items.length} users</h2></div><div className="section-head-actions"><button className="secondary" onClick={load}>Refresh</button><button className="primary" onClick={()=>setShowCreate(true)}>+ New user</button></div></div>
 {items.length===0?<p className="muted">No users available.</p>:<div className="record-list">{items.map(u=><div className="record" key={u.id}><div><strong>{u.displayName}</strong><span>@{u.username} · {u.role}</span><small className={u.active?'':'muted'}>{u.active?'Active':'Inactive'}</small></div><div className="actions"><button className={u.active?'secondary small':'primary small'} disabled={busy===u.id} onClick={()=>toggle(u)}>{busy===u.id?'Saving…':u.active?'Deactivate':'Reactivate'}</button><button className="secondary small" disabled={busy===u.id} onClick={()=>setEditUser(u)}>Edit</button>{u.active&&<button className="secondary small" disabled={busy===u.id} onClick={()=>setResetUser(u)}>Reset password</button>}</div></div>)}</div>}
 </section>
 {editUser&&<EditUserForm user={editUser} currentUsername={currentUsername} onCancel={()=>setEditUser(null)} onSaved={u=>{setItems(xs=>xs.map(x=>x.id===u.id?u:x));setEditUser(null)}}/>}{showCreate&&<UserForm onCancel={()=>setShowCreate(false)} onSaved={u=>{setItems(xs=>[...xs,u].sort((x,y)=>x.username.localeCompare(y.username)));setShowCreate(false)}}/>}{resetUser&&<ResetUserPasswordForm user={resetUser} onCancel={()=>setResetUser(null)} onSaved={()=>setResetUser(null)}/>}
 </main>
}
function EditUserForm({user,currentUsername,onCancel,onSaved}:{user:import('./api').ShelterUser;currentUsername:string;onCancel:()=>void;onSaved:(u:import('./api').ShelterUser)=>void}){
 const currentUsername=localStorage.getItem('shelterUsername')||'';
 const [f,setF]=useState({displayName:user.displayName,role:user.role}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(){if(!f.displayName.trim()){setError('Display name is required');return}setBusy(true);setError('');try{onSaved(await updateUser(user.id,{displayName:f.displayName,role:f.role}))}catch(e){setError(e instanceof Error?e.message:'Could not update user')}finally{setBusy(false)}}
 return <FormShell eyebrow="USER MANAGEMENT" title={'Edit user · '+user.username} onCancel={onCancel}><div className="form-grid"><label>Display name *<input value={f.displayName} onChange={e=>setF(x=>({...x,displayName:e.target.value}))}/></label><label>Role<select value={f.role} disabled={user.username.toLowerCase()===currentUsername.toLowerCase()} onChange={e=>setF(x=>({...x,role:e.target.value}))}><option>ADMIN</option><option>VETERINARIAN</option><option>COORDINATOR</option><option>VOLUNTEER</option><option>VIEWER</option></select>{user.username.toLowerCase()===currentUsername.toLowerCase()&&<small className="muted">Your own role cannot be changed here.</small>}</label></div>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save changes'}</button></FormShell>
}
function ResetUserPasswordForm({user,onCancel,onSaved}:{user:import('./api').ShelterUser;onCancel:()=>void;onSaved:()=>void}){
 const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(){if(password.length<12){setError('Password must be at least 12 characters');return}if(password!==confirm){setError('Passwords do not match');return}setBusy(true);setError('');try{await resetUserPassword(user.id,password);onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not reset password')}finally{setBusy(false)}}
 return <FormShell eyebrow="USER MANAGEMENT" title={'Reset password · '+user.displayName} onCancel={onCancel}><div className="form-grid"><label>New password *<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></label><label>Confirm password *<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label></div><p className="muted">This immediately replaces the user's password. The new password is not displayed or stored in the interface.</p>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Resetting…':'Reset password'}</button></FormShell>
}
function UserForm({onCancel,onSaved}:{onCancel:()=>void;onSaved:(u:import('./api').ShelterUser)=>void}){
 const [f,setF]=useState({username:'',displayName:'',password:'',role:'VOLUNTEER'}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const set=(k:keyof typeof f,v:string)=>setF(x=>({...x,[k]:v}))
 async function save(){if(!f.username||!f.displayName||f.password.length<12){setError('Username, display name and a password of at least 12 characters are required');return}setBusy(true);setError('');try{onSaved(await createUser(f))}catch(e){setError(e instanceof Error?e.message:'Could not create user')}finally{setBusy(false)}}
 return <FormShell eyebrow="USER MANAGEMENT" title="Create user" onCancel={onCancel}><div className="form-grid"><label>Username *<input value={f.username} onChange={e=>set('username',e.target.value)} autoComplete="off"/></label><label>Display name *<input value={f.displayName} onChange={e=>set('displayName',e.target.value)}/></label><label>Role<select value={f.role} onChange={e=>set('role',e.target.value)}><option>ADMIN</option><option>VETERINARIAN</option><option>COORDINATOR</option><option>VOLUNTEER</option><option>VIEWER</option></select></label><label>Password *<input type="password" value={f.password} onChange={e=>set('password',e.target.value)} autoComplete="new-password"/></label></div>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Creating…':'Create user'}</button></FormShell>
}

function Audit({onBack,onLogout}:{onBack:()=>void;onLogout:()=>void}){
 const [items,setItems]=useState<import('./api').AuditLog[]>([]),[error,setError]=useState('');
 async function load(){try{setItems(await getAuditLogs());setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load audit log')}}
 useEffect(()=>{load()},[])
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">ADMINISTRATION</p><h1>Audit log</h1><p className="muted">Recent recorded actions in the shelter system</p></div><div className="top-actions"><button className="secondary" onClick={onBack}>Dashboard</button><button className="secondary" onClick={onLogout}>Sign out</button></div></header>{error&&<div className="error">{error}</div>}<section className="panel"><div className="section-head"><div><p className="eyebrow">ACTIVITY</p><h2>{items.length} entries</h2></div><button className="secondary" onClick={load}>Refresh</button></div>{items.length===0?<p className="muted">No audit entries recorded.</p>:<div className="record-list">{items.map(x=><div className="record" key={x.id}><strong>{x.action}</strong><span>{new Date(x.occurredAt).toLocaleString()} · {x.actor} · {x.entityType}{x.entityId?' · '+x.entityId:''}</span>{x.details&&<small>{x.details}</small>}</div>)}</div>}</section></main>
}

function TaskForm({onCancel,onSaved}:{onCancel:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({taskType:'GENERAL',title:'',dueAt:'',priority:'NORMAL',assignedTo:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));async function save(){if(!f.title||!f.dueAt){setError('Title and due date are required');return}setBusy(true);try{await createTask({taskType:f.taskType,title:f.title,dueAt:new Date(f.dueAt).toISOString(),priority:f.priority,assignedTo:f.assignedTo||undefined,notes:f.notes||undefined});onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not create task')}finally{setBusy(false)}}return <FormShell eyebrow="TASKS & REMINDERS" title="New task / reminder" onCancel={onCancel}><div className="form-grid"><label>Type<select value={f.taskType} onChange={e=>set('taskType',e.target.value)}><option value="GENERAL">General</option><option value="VACCINATION_DUE">Vaccination due</option><option value="DEWORMING_DUE">Deworming due</option><option value="VET_VISIT">Vet visit</option><option value="TREATMENT">Treatment</option></select></label><label>Priority<select value={f.priority} onChange={e=>set('priority',e.target.value)}><option value="LOW">Low</option><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label><label className="span-2">Title *<input value={f.title} onChange={e=>set('title',e.target.value)} placeholder="e.g. Book follow-up blood test"/></label><label>Due date & time *<input type="datetime-local" value={f.dueAt} onChange={e=>set('dueAt',e.target.value)}/></label><label>Assigned to<input value={f.assignedTo} onChange={e=>set('assignedTo',e.target.value)} placeholder="Username (optional)"/></label><label className="span-2">Notes<textarea rows={3} value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Create task'}</button></FormShell>}

function Stat({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <article className={'stat '+(danger?'stat-danger':'')}><span>{label}</span><strong>{value}</strong></article>}

function Animals({onBack,onLogout}:{onBack:()=>void;onLogout:()=>void}){
 const [animals,setAnimals]=useState<Animal[]>([]),[selected,setSelected]=useState<Animal|null>(null),[editing,setEditing]=useState(false),[creating,setCreating]=useState(false),[treatments,setTreatments]=useState<Treatment[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('')
 async function load(){try{setAnimals(await getAnimals(query));setError('')}catch(e){if(e instanceof Error&&e.message!=='Authentication required')setError('Could not load animals')}}
 useEffect(()=>{load()},[]); useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[query])
 async function select(a:Animal){setSelected(a);setEditing(false);try{setTreatments(await getTreatments(a.id))}catch{setTreatments([])}}
 function saved(a:Animal){setAnimals(xs=>{const found=xs.some(x=>x.id===a.id);return found?xs.map(x=>x.id===a.id?a:x):[...xs,a].sort((x,y)=>x.name.localeCompare(y.name))});setSelected(a);setCreating(false);setEditing(false)}
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">SHELTER MANAGEMENT</p><h1>{selected?selected.name:'Animals'}</h1><p className="muted">{selected?'Animal profile':'Every animal, its history and care.'}</p></div><div className="top-actions"><button className="secondary" onClick={onBack}>Dashboard</button>{selected&&!creating&&<button className="secondary" onClick={()=>setSelected(null)}>← All animals</button>}<button className="secondary" onClick={onLogout}>Sign out</button></div></header>
 {!selected&&!creating&&<><section className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, ID or microchip…"/><span className="muted">{animals.length} animals</span><button className="primary" onClick={()=>setCreating(true)}>+ Add animal</button></section>{error&&<div className="error">{error}</div>}<section className="animal-list">{animals.map(a=><button className="animal-card clickable" key={a.id} onClick={()=>select(a)}>{a.photoUrl?<img className="avatar photo" src={a.photoUrl} alt=""/>:<div className="avatar">{a.name.charAt(0).toUpperCase()}</div>}<div className="animal-main"><h2>{a.name}</h2><p>{a.animalCode} · {a.animalType} · {a.sex} · {a.weightKg?a.weightKg+' kg':'weight not recorded'}</p><p className="muted">{a.location||'No location'} · {a.status}</p></div><span className="chip">{a.microchipNumber||'No chip'}</span></button>)}{animals.length===0&&<div className="empty">No animals registered yet.</div>}</section></>}
 {creating&&<AnimalForm onCancel={()=>setCreating(false)} onSaved={saved}/>}
 {selected&&!creating&&(editing?<AnimalForm animal={selected} onCancel={()=>setEditing(false)} onSaved={saved}/>:<AnimalProfile animal={selected} treatments={treatments} onEdit={()=>setEditing(true)}/>)}
 </main>
}

function AnimalForm({animal,onCancel,onSaved}:{animal?:Animal;onCancel:()=>void;onSaved:(a:Animal)=>void}){
 const [form,setForm]=useState<AnimalInput>(animal?{name:animal.name,animalType:animal.animalType,sex:animal.sex,dateOfBirth:animal.dateOfBirth||'',weightKg:animal.weightKg,microchipNumber:animal.microchipNumber||'',intakeDate:animal.intakeDate,rescueSource:animal.rescueSource||'',location:animal.location||'',status:animal.status,notes:animal.notes||'',photoUrl:animal.photoUrl||''}:blankAnimal())
 const [error,setError]=useState(''),[saving,setSaving]=useState(false)
 const set=(k:keyof AnimalInput,v:any)=>setForm(f=>({...f,[k]:v}))
 async function submit(e:FormEvent){e.preventDefault();if(!form.name.trim()||!form.animalType||!form.sex||!form.intakeDate){setError('Name, type, sex and intake date are required.');return}setSaving(true);setError('');try{const a=animal?await updateAnimal(animal.id,form):await createAnimal(form);onSaved(a)}catch(e){setError(e instanceof Error?e.message:'Could not save animal')}finally{setSaving(false)}}
 return <form className="panel animal-form" onSubmit={submit}><div className="form-head"><div><p className="eyebrow">{animal?'EDIT ANIMAL':'NEW ANIMAL'}</p><h2>{animal?'Edit '+animal.name:'Add animal'}</h2>{animal&&<p className="muted">ID: {animal.animalCode}</p>}</div><div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save animal'}</button></div></div>
 <div className="form-grid"><label>Name *<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="e.g. Luna"/></label><label>Animal type *<select value={form.animalType} onChange={e=>set('animalType',e.target.value)}><option value="DOG">Dog</option><option value="CAT">Cat</option><option value="OTHER">Other</option></select></label><label>Sex *<select value={form.sex} onChange={e=>set('sex',e.target.value)}><option value="UNKNOWN">Unknown</option><option value="FEMALE">Female</option><option value="MALE">Male</option></select></label><label>Weight (kg)<input type="number" min="0.001" step="0.001" value={form.weightKg??''} onChange={e=>set('weightKg',e.target.value?Number(e.target.value):undefined)}/></label><label>Date of birth<input type="date" value={form.dateOfBirth||''} onChange={e=>set('dateOfBirth',e.target.value)}/></label><label>Intake date *<input type="date" value={form.intakeDate} onChange={e=>set('intakeDate',e.target.value)}/></label><label>Microchip<input value={form.microchipNumber||''} onChange={e=>set('microchipNumber',e.target.value)} placeholder="Microchip number"/></label><label>Location / kennel<input value={form.location||''} onChange={e=>set('location',e.target.value)} placeholder="Kennel A-12"/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="ACTIVE">Active</option><option value="TREATMENT">Treatment</option><option value="HEALTHY">Healthy</option><option value="QUARANTINE">Quarantine</option><option value="FOSTER">Foster</option><option value="ADOPTED">Adopted</option></select></label><label>Rescue source<input value={form.rescueSource||''} onChange={e=>set('rescueSource',e.target.value)} placeholder="Street / shelter / owner surrender"/></label><label className="span-2">Photo URL<input value={form.photoUrl||''} onChange={e=>set('photoUrl',e.target.value)} placeholder="https://…"/></label><label className="span-2">Notes<textarea rows={5} value={form.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="Medical or operational notes…"/></label></div>{form.photoUrl&&<div className="photo-preview"><img src={form.photoUrl} alt="Animal preview"/></div>}{error&&<div className="inline-error">{error}</div>}</form>
}

function AnimalProfile({animal,treatments,onEdit}:{animal:Animal;treatments:Treatment[];onEdit:()=>void}){
 const [activeTab,setActiveTab]=useState('Overview')
 const [events,setEvents]=useState<MedicalEvent[]>([]),[vaccines,setVaccines]=useState<Vaccination[]>([]),[dewormings,setDewormings]=useState<Deworming[]>([]),[documents,setDocuments]=useState<MedicalDocument[]>([])
 const [showEvent,setShowEvent]=useState(false),[showVaccine,setShowVaccine]=useState(false),[showDeworm,setShowDeworm]=useState(false),[showDocument,setShowDocument]=useState(false)
 async function loadMedical(){try{setEvents(await getMedicalEvents(animal.id));setVaccines(await getVaccinations(animal.id));setDewormings(await getDewormings(animal.id));setDocuments(await getDocuments(animal.id))}catch{}}
 useEffect(()=>{loadMedical()},[animal.id])
 return <div className="profile"><section className="profile-hero">{animal.photoUrl?<img className="big-avatar photo" src={animal.photoUrl} alt=""/>:<div className="big-avatar">{animal.name.charAt(0).toUpperCase()}</div>}<div><p className="eyebrow">{animal.animalType} · {animal.animalCode}</p><h2>{animal.name}</h2><p className="muted">{animal.status} · {animal.location||'No location'}</p></div><button className="secondary edit-button" onClick={onEdit}>Edit animal</button></section>
 <nav className="tabs">{['Overview','Medical','Treatments','Vaccines','Deworming','Vet visits','Documents'].map(tab=><button key={tab} className={activeTab===tab?'active':''} onClick={()=>setActiveTab(tab)}>{tab}</button>)}</nav>
 {activeTab==='Overview'&&<section className="profile-grid"><article className="panel"><p className="eyebrow">IDENTITY</p><dl><dt>Animal ID</dt><dd>{animal.animalCode}</dd><dt>Sex</dt><dd>{animal.sex}</dd><dt>Weight</dt><dd>{animal.weightKg?animal.weightKg+' kg':'—'}</dd><dt>Microchip</dt><dd>{animal.microchipNumber||'—'}</dd><dt>Date of birth</dt><dd>{animal.dateOfBirth||'—'}</dd><dt>Intake</dt><dd>{animal.intakeDate}</dd><dt>Rescue source</dt><dd>{animal.rescueSource||'—'}</dd></dl></article><article className="panel"><p className="eyebrow">ACTIVE TREATMENTS</p>{treatments.length===0?<p className="muted">No treatment plans recorded.</p>:<div className="treatment-list">{treatments.map(t=><TreatmentCard key={t.id} animalId={animal.id} treatment={t}/>)}</div>}</article></section>}
 {activeTab==='Medical'&&<MedicalTab events={events} onAdd={()=>setShowEvent(true)}/>}
 {activeTab==='Vaccines'&&<VaccineTab items={vaccines} onAdd={()=>setShowVaccine(true)}/>}
 {activeTab==='Deworming'&&<DewormingTab items={dewormings} onAdd={()=>setShowDeworm(true)}/>}
 {activeTab==='Vet visits'&&<MedicalTab events={events.filter(e=>e.eventType==='VET_VISIT')} onAdd={()=>setShowEvent(true)}/>}
 {activeTab==='Treatments'&&<section className="treatment-list full-width">{treatments.length===0?<div className="panel"><p className="muted">No treatment plans recorded.</p></div>:treatments.map(t=><TreatmentCard key={t.id} animalId={animal.id} treatment={t} expanded/>)}</section>}
 {activeTab==='Documents'&&<DocumentsTab items={documents} onAdd={()=>setShowDocument(true)}/>}
 {animal.notes&&activeTab==='Overview'&&<section className="panel notes"><p className="eyebrow">NOTES</p><p>{animal.notes}</p></section>}
 {showEvent&&<MedicalEventForm animalId={animal.id} onCancel={()=>setShowEvent(false)} onSaved={()=>{setShowEvent(false);loadMedical()}}/>}
 {showVaccine&&<VaccineForm animalId={animal.id} onCancel={()=>setShowVaccine(false)} onSaved={()=>{setShowVaccine(false);loadMedical()}}/>}
 {showDeworm&&<DewormingForm animalId={animal.id} onCancel={()=>setShowDeworm(false)} onSaved={()=>{setShowDeworm(false);loadMedical()}}/>}{showDocument&&<DocumentForm animalId={animal.id} onCancel={()=>setShowDocument(false)} onSaved={()=>{setShowDocument(false);loadMedical()}}/>}
 </div>
}
function TreatmentCard({animalId,treatment,expanded=false}:{animalId:string;treatment:Treatment;expanded?:boolean}){
 const [administrations,setAdministrations]=useState<Administration[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function load(){try{setAdministrations(await getAdministrations(animalId,treatment.id));setError('')}catch{setError('Could not load schedule')}} useEffect(()=>{load()},[animalId,treatment.id])
 async function generate(){setBusy(true);try{await generateAdministrations(animalId,treatment.id,14);await load()}catch(e){setError(e instanceof Error?e.message:'Could not generate schedule')}finally{setBusy(false)}}
 async function act(a:Administration){setBusy(true);try{await administer(animalId,treatment.id,a.id);await load()}catch(e){setError(e instanceof Error?e.message:'Could not record administration')}finally{setBusy(false)}}
 async function mark(a:Administration,status:'MISSED'|'SKIPPED'){setBusy(true);try{await setAdministrationStatus(animalId,treatment.id,a.id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Could not update administration')}finally{setBusy(false)}}
 return <div className="treatment"><div className="treatment-head"><div><strong>{treatment.medication}</strong><span>{treatment.dose} · {treatment.route} · {treatment.frequency}</span><small>{treatment.startDate}{treatment.endDate?' → '+treatment.endDate:''}</small></div><button className="secondary small" disabled={busy} onClick={generate}>{busy?'…':'Generate schedule'}</button></div>{error&&<div className="inline-error">{error}</div>}{expanded&&administrations.length>0&&<div className="administrations">{administrations.slice(0,30).map(a=><div className="administration" key={a.id}><div><strong>{new Date(a.scheduledAt).toLocaleString()}</strong><small>{a.status}{a.administeredAt?' · '+new Date(a.administeredAt).toLocaleTimeString()+' · '+a.administeredBy:''}</small></div>{a.status==='SCHEDULED'&&<div className="actions"><button className="primary small" disabled={busy} onClick={()=>act(a)}>ADMINISTER</button><button className="secondary small" disabled={busy} onClick={()=>mark(a,'SKIPPED')}>Skip</button></div>}</div>)}</div>}{!expanded&&administrations.length>0&&<div className="next-dose"><span>Next: {new Date(administrations.find(a=>a.status==='SCHEDULED')?.scheduledAt||administrations[0].scheduledAt).toLocaleString()}</span><span className="chip">{administrations.filter(a=>a.status==='ADMINISTERED').length} administered</span></div>}</div>
}

function MedicalTab({events,onAdd}:{events:MedicalEvent[];onAdd:()=>void}){return <section className="panel"><div className="section-head"><div><p className="eyebrow">MEDICAL HISTORY</p><h2>Clinical records</h2></div><button className="primary small" onClick={onAdd}>+ Add record</button></div>{events.length===0?<p className="muted">No medical records.</p>:<div className="record-list">{events.map(e=><div className="record" key={e.id}><div><strong>{e.title}</strong><span>{e.eventDate} · {e.eventType.replace('_',' ')}</span>{e.diagnosis&&<small>Diagnosis: {e.diagnosis}</small>}{e.provider&&<small>Provider: {e.provider}</small>}{e.notes&&<small>{e.notes}</small>}</div></div>)}</div>}</section>}
function VaccineTab({items,onAdd}:{items:Vaccination[];onAdd:()=>void}){return <section className="panel"><div className="section-head"><div><p className="eyebrow">VACCINATION</p><h2>Vaccination history</h2></div><button className="primary small" onClick={onAdd}>+ Add vaccine</button></div>{items.length===0?<p className="muted">No vaccinations recorded.</p>:<div className="record-list">{items.map(v=><div className="record" key={v.id}><strong>{v.vaccineName}</strong><span>{v.administeredDate}{v.nextDueDate?' · next due '+v.nextDueDate:''}</span><small>{[v.vaccineType,v.batchNumber,v.veterinarian].filter(Boolean).join(' · ')}</small></div>)}</div>}</section>}
function DewormingTab({items,onAdd}:{items:Deworming[];onAdd:()=>void}){return <section className="panel"><div className="section-head"><div><p className="eyebrow">DEWORMING</p><h2>Antiparasitic history</h2></div><button className="primary small" onClick={onAdd}>+ Add treatment</button></div>{items.length===0?<p className="muted">No deworming records.</p>:<div className="record-list">{items.map(d=><div className="record" key={d.id}><strong>{d.productName}</strong><span>{d.administeredDate}{d.nextDueDate?' · next due '+d.nextDueDate:''}</span><small>{[d.treatmentType,d.dose,d.veterinarian].filter(Boolean).join(' · ')}</small></div>)}</div>}</section>}
function DocumentsTab({items,onAdd}:{items:MedicalDocument[];onAdd:()=>void}){return <section className="panel"><div className="section-head"><div><p className="eyebrow">DOCUMENTS</p><h2>Medical documents</h2></div><button className="primary small" onClick={onAdd}>+ Add document</button></div>{items.length===0?<p className="muted">No documents recorded.</p>:<div className="record-list">{items.map(d=><div className="record" key={d.id}><strong><a href={d.fileUrl} target="_blank" rel="noreferrer">{d.title}</a></strong><span>{d.documentType}{d.documentDate?' · '+d.documentDate:''}</span>{d.notes&&<small>{d.notes}</small>}{d.uploadedBy&&<small>Added by {d.uploadedBy}</small>}</div>)}</div>}<p className="muted document-hint">Files are stored on the shelter server; metadata remains in PostgreSQL.</p></section>}

function DocumentForm({animalId,onCancel,onSaved}:{animalId:string;onCancel:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({documentType:'LAB_RESULT',title:'',documentDate:today(),notes:''}),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));async function save(){if(!f.title||!file){setError('Title and file are required');return}setBusy(true);try{await uploadDocument(animalId,file,f);onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not upload document')}finally{setBusy(false)}}return <FormShell title="Upload document" onCancel={onCancel}><div className="form-grid"><label>Type<select value={f.documentType} onChange={e=>set('documentType',e.target.value)}><option value="LAB_RESULT">Lab result</option><option value="VET_REPORT">Vet report</option><option value="VACCINE_CERTIFICATE">Vaccine certificate</option><option value="OTHER">Other</option></select></label><label>Date<input type="date" value={f.documentDate} onChange={e=>set('documentDate',e.target.value)}/></label><label className="span-2">Title *<input value={f.title} onChange={e=>set('title',e.target.value)}/></label><label className="span-2">File *<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="span-2">Notes<textarea rows={3} value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div><p className="muted document-hint">PDF, images and common document formats. Maximum 25 MB.</p>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Uploading…':'Upload document'}</button></FormShell>}

function FormShell({eyebrow="MEDICAL RECORD",title,onCancel,children}:{eyebrow?:string;title:string;onCancel:()=>void;children:ReactNode}){return <div className="modal-backdrop"><form className="panel modal-card" onSubmit={e=>e.preventDefault()}><div className="form-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button type="button" className="secondary small" onClick={onCancel}>Close</button></div>{children}</form></div>}
function MedicalEventForm({animalId,onCancel,onSaved}:{animalId:string;onCancel:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({eventType:'VET_VISIT',eventDate:today(),title:'',diagnosis:'',provider:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));async function save(){if(!f.title){setError('Title is required');return}setBusy(true);try{await createMedicalEvent(animalId,f);onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}return <FormShell title="Add clinical record" onCancel={onCancel}><div className="form-grid"><label>Type<select value={f.eventType} onChange={e=>set('eventType',e.target.value)}><option value="VET_VISIT">Vet visit</option><option value="DIAGNOSIS">Diagnosis</option><option value="LAB_RESULT">Lab result</option><option value="OTHER">Other</option></select></label><label>Date<input type="date" value={f.eventDate} onChange={e=>set('eventDate',e.target.value)}/></label><label className="span-2">Title *<input value={f.title} onChange={e=>set('title',e.target.value)}/></label><label>Diagnosis<input value={f.diagnosis} onChange={e=>set('diagnosis',e.target.value)}/></label><label>Veterinarian / provider<input value={f.provider} onChange={e=>set('provider',e.target.value)}/></label><label className="span-2">Notes<textarea rows={4} value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save record'}</button></FormShell>}
function VaccineForm({animalId,onCancel,onSaved}:{animalId:string;onCancel:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({vaccineName:'',vaccineType:'',administeredDate:today(),nextDueDate:'',batchNumber:'',veterinarian:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));async function save(){if(!f.vaccineName){setError('Vaccine name is required');return}setBusy(true);try{await createVaccination(animalId,f);onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}return <FormShell title="Add vaccination" onCancel={onCancel}><div className="form-grid"><label>Vaccine *<input value={f.vaccineName} onChange={e=>set('vaccineName',e.target.value)}/></label><label>Type<input value={f.vaccineType} onChange={e=>set('vaccineType',e.target.value)}/></label><label>Date *<input type="date" value={f.administeredDate} onChange={e=>set('administeredDate',e.target.value)}/></label><label>Next due<input type="date" value={f.nextDueDate} onChange={e=>set('nextDueDate',e.target.value)}/></label><label>Batch number<input value={f.batchNumber} onChange={e=>set('batchNumber',e.target.value)}/></label><label>Veterinarian<input value={f.veterinarian} onChange={e=>set('veterinarian',e.target.value)}/></label><label className="span-2">Notes<textarea rows={3} value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save vaccination'}</button></FormShell>}
function DewormingForm({animalId,onCancel,onSaved}:{animalId:string;onCancel:()=>void;onSaved:()=>void}){const [f,setF]=useState<any>({productName:'',treatmentType:'',administeredDate:today(),nextDueDate:'',dose:'',veterinarian:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k:string,v:string)=>setF((x:any)=>({...x,[k]:v}));async function save(){if(!f.productName){setError('Product name is required');return}setBusy(true);try{await createDeworming(animalId,f);onSaved()}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}return <FormShell title="Add deworming" onCancel={onCancel}><div className="form-grid"><label>Product *<input value={f.productName} onChange={e=>set('productName',e.target.value)}/></label><label>Type<input value={f.treatmentType} onChange={e=>set('treatmentType',e.target.value)}/></label><label>Date *<input type="date" value={f.administeredDate} onChange={e=>set('administeredDate',e.target.value)}/></label><label>Next due<input type="date" value={f.nextDueDate} onChange={e=>set('nextDueDate',e.target.value)}/></label><label>Dose<input value={f.dose} onChange={e=>set('dose',e.target.value)}/></label><label>Veterinarian<input value={f.veterinarian} onChange={e=>set('veterinarian',e.target.value)}/></label><label className="span-2">Notes<textarea rows={3} value={f.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{error&&<div className="inline-error">{error}</div>}<button type="button" className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save deworming'}</button></FormShell>}
