import {useEffect,useState} from 'react'
import {DashboardItem,getDashboard} from './dashboard'
import {Animal,AnimalInput,Treatment,Administration,getAnimals,getTreatments,getAdministrations,generateAdministrations,administer,setAdministrationStatus,createAnimal,updateAnimal} from './api'

const today=()=>new Date().toISOString().slice(0,10)
const blankAnimal=():AnimalInput=>({name:'',animalType:'DOG',sex:'UNKNOWN',dateOfBirth:'',weightKg:undefined,microchipNumber:'',intakeDate:today(),rescueSource:'',location:'',status:'ACTIVE',notes:'',photoUrl:''})

export default function App(){
 const [authenticated,setAuthenticated]=useState(!!localStorage.getItem('shelterAuth'))
 useEffect(()=>{const h=()=>setAuthenticated(false);window.addEventListener('shelter-auth-required',h);return()=>window.removeEventListener('shelter-auth-required',h)},[])
 return authenticated?<ShelterApp onLogout={()=>{localStorage.removeItem('shelterAuth');setAuthenticated(false)}}/>:<Login onLogin={()=>setAuthenticated(true)}/>
}
function Login({onLogin}:{onLogin:()=>void}){
 const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[error,setError]=useState('')
 async function submit(e:React.FormEvent){e.preventDefault();const token=btoa(username+':'+password);const r=await fetch('/api/animals',{headers:{Authorization:'Basic '+token}});if(!r.ok){setError('Invalid username or password');return}localStorage.setItem('shelterAuth',token);onLogin()}
 return <main className="login-shell"><form className="login-card" onSubmit={submit}><p className="eyebrow">SHELTER MANAGEMENT</p><h1>Sign in</h1><p className="muted">Access the animal care system.</p><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" autoComplete="username"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password" autoComplete="current-password"/>{error&&<div className="inline-error">{error}</div>}<button className="primary" type="submit">Sign in</button></form></main>
}
function ShelterApp({onLogout}:{onLogout:()=>void}){
 const [view,setView]=useState<'dashboard'|'animals'>('dashboard')
 if(view==='dashboard')return <Dashboard onOpenAnimals={()=>setView('animals')} onLogout={onLogout}/>
 return <Animals onBack={()=>setView('dashboard')} onLogout={onLogout}/>
}
function Dashboard({onOpenAnimals,onLogout}:{onOpenAnimals:()=>void;onLogout:()=>void}){
 const [data,setData]=useState<{items:DashboardItem[];overdue:number;remaining:number;administered:number}|null>(null),[error,setError]=useState('')
 async function load(){try{setData(await getDashboard());setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load dashboard')}}
 useEffect(()=>{load();const t=setInterval(load,60000);return()=>clearInterval(t)},[])
 const pending=data?.items.filter(x=>x.status==='SCHEDULED')||[], overdue=pending.filter(x=>new Date(x.scheduledAt)<new Date())
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">SHELTER MANAGEMENT</p><h1>Today</h1><p className="muted">Operational care dashboard</p></div><div className="top-actions"><button className="secondary" onClick={onOpenAnimals}>Animals</button><button className="secondary" onClick={onLogout}>Sign out</button></div></header>
 {error&&<div className="error">{error}</div>}<section className="dashboard-stats"><Stat label="Overdue" value={data?.overdue??'—'} danger/><Stat label="Remaining" value={data?.remaining??'—'}/><Stat label="Administered" value={data?.administered??'—'}/></section>
 <section className="panel dashboard-panel"><div className="section-head"><div><p className="eyebrow">ACTION QUEUE</p><h2>{overdue.length?'Overdue administrations':'Upcoming administrations'}</h2></div><span className="muted">{overdue.length?'Needs attention':'Today'}</span></div>{(overdue.length?overdue:pending).length===0?<p className="muted">No scheduled administrations for today.</p>:<div className="dashboard-list">{(overdue.length?overdue:pending).slice(0,20).map(x=><div className="dashboard-item" key={x.id}><div><strong>{x.animalName}</strong><span>{x.medication} · {x.dose} · {x.route}</span></div><div className="dashboard-time">{new Date(x.scheduledAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{overdue.includes(x)&&<span className="overdue-badge">OVERDUE</span>}</div></div>)}</div>}</section>
 <section className="panel dashboard-panel"><div className="section-head"><div><p className="eyebrow">TODAY</p><h2>Administration timeline</h2></div></div><div className="dashboard-list">{(data?.items||[]).slice(0,30).map(x=><div className="dashboard-item" key={x.id}><div><strong>{x.animalName}</strong><span>{x.medication} · {x.dose}</span></div><span className={'status status-'+x.status.toLowerCase()}>{x.status}</span></div>)}</div></section></main>
}
function Stat({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <article className={'stat '+(danger?'stat-danger':'')}><span>{label}</span><strong>{value}</strong></article>}

function Animals({onBack,onLogout}:{onBack:()=>void;onLogout:()=>void}){
 const [animals,setAnimals]=useState<Animal[]>([]),[selected,setSelected]=useState<Animal|null>(null),[editing,setEditing]=useState(false),[creating,setCreating]=useState(false),[treatments,setTreatments]=useState<Treatment[]>([]),[query,setQuery]=useState(''),[error,setError]=useState('')
 async function load(){try{setAnimals(await getAnimals(query));setError('')}catch(e){if(e instanceof Error&&e.message!=='Authentication required')setError('Could not load animals')}}
 useEffect(()=>{load()},[]); useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[query])
 async function select(a:Animal){setSelected(a);setEditing(false);try{setTreatments(await getTreatments(a.id))}catch{setTreatments([])}}
 function saved(a:Animal){setAnimals(xs=>{const found=xs.some(x=>x.id===a.id);return found?xs.map(x=>x.id===a.id?a:x):[...xs,a].sort((x,y)=>x.name.localeCompare(y.name))});setSelected(a);setCreating(false);setEditing(false)}
 return <main className="shell"><header className="topbar"><div><p className="eyebrow">SHELTER MANAGEMENT</p><h1>{selected?selected.name:'Animals'}</h1><p className="muted">{selected?'Animal profile':'Every animal, its history and care.'}</p></div><div className="top-actions"><button className="secondary" onClick={onBack}>Dashboard</button>{selected&&!creating&&<button className="secondary" onClick={()=>setSelected(null)}>← All animals</button>}<button className="secondary" onClick={onLogout}>Sign out</button></div></header>
 {!selected&&!creating&&<><section className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, ID or microchip…"/><span className="muted">{animals.length} animals</span><button className="primary" onClick={()=>setCreating(true)}>+ Add animal</button></section>{error&&<div className="error">{error}</div>}<section className="animal-list">{animals.map(a=><button className="animal-card clickable" key={a.id} onClick={()=>select(a)}>{a.photoUrl?<img className="avatar photo" src={a.photoUrl} alt=""/>:<div className="avatar">{a.name.charAt(0).toUpperCase()}</div>}<div className="animal-main"><h2>{a.name}</h2><p>{a.animalCode} · {a.animalType} · {a.sex} · {a.weightKg?a.weightKg+' kg':'weight not recorded'}</p><p className="muted">{a.location||'No location'} · {a.status}</p></div><span className="chip">{a.microchipNumber||'No chip'}</span></button>)}{animals.length===0&&<div className="empty">No animals registered yet.</div>}</section></>}
 {creating&&<AnimalForm onCancel={()=>setCreating(false)} onSaved={saved}/>}
 {selected&&!creating&&(editing?<AnimalForm animal={selected} onCancel={()=>setEditing(false)} onSaved={saved}/>:<AnimalProfile animal={selected} treatments={treatments} onEdit={()=>setEditing(true)}/>)}
 </main>
}

function AnimalForm({animal,onCancel,onSaved}:{animal?:Animal;onCancel:()=>void;onSaved:(a:Animal)=>void}){
 const [form,setForm]=useState<AnimalInput>(animal?{name:animal.name,animalType:animal.animalType,sex:animal.sex,dateOfBirth:animal.dateOfBirth||'',weightKg:animal.weightKg,microchipNumber:animal.microchipNumber||'',intakeDate:animal.intakeDate,rescueSource:animal.rescueSource||'',location:animal.location||'',status:animal.status,notes:animal.notes||'',photoUrl:animal.photoUrl||''}:blankAnimal())
 const [error,setError]=useState(''),[saving,setSaving]=useState(false)
 const set=(k:keyof AnimalInput,v:any)=>setForm(f=>({...f,[k]:v}))
 async function submit(e:React.FormEvent){e.preventDefault();if(!form.name.trim()||!form.animalType||!form.sex||!form.intakeDate){setError('Name, type, sex and intake date are required.');return}setSaving(true);setError('');try{const a=animal?await updateAnimal(animal.id,form):await createAnimal(form);onSaved(a)}catch(e){setError(e instanceof Error?e.message:'Could not save animal')}finally{setSaving(false)}}
 return <form className="panel animal-form" onSubmit={submit}><div className="form-head"><div><p className="eyebrow">{animal?'EDIT ANIMAL':'NEW ANIMAL'}</p><h2>{animal?'Edit '+animal.name:'Add animal'}</h2>{animal&&<p className="muted">ID: {animal.animalCode}</p>}</div><div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save animal'}</button></div></div>
 <div className="form-grid"><label>Name *<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="e.g. Luna"/></label><label>Animal type *<select value={form.animalType} onChange={e=>set('animalType',e.target.value)}><option value="DOG">Dog</option><option value="CAT">Cat</option><option value="OTHER">Other</option></select></label><label>Sex *<select value={form.sex} onChange={e=>set('sex',e.target.value)}><option value="UNKNOWN">Unknown</option><option value="FEMALE">Female</option><option value="MALE">Male</option></select></label><label>Weight (kg)<input type="number" min="0.001" step="0.001" value={form.weightKg??''} onChange={e=>set('weightKg',e.target.value?Number(e.target.value):undefined)}/></label><label>Date of birth<input type="date" value={form.dateOfBirth||''} onChange={e=>set('dateOfBirth',e.target.value)}/></label><label>Intake date *<input type="date" value={form.intakeDate} onChange={e=>set('intakeDate',e.target.value)}/></label><label>Microchip<input value={form.microchipNumber||''} onChange={e=>set('microchipNumber',e.target.value)} placeholder="Microchip number"/></label><label>Location / kennel<input value={form.location||''} onChange={e=>set('location',e.target.value)} placeholder="Kennel A-12"/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}><option value="ACTIVE">Active</option><option value="TREATMENT">Treatment</option><option value="HEALTHY">Healthy</option><option value="QUARANTINE">Quarantine</option><option value="FOSTER">Foster</option><option value="ADOPTED">Adopted</option></select></label><label>Rescue source<input value={form.rescueSource||''} onChange={e=>set('rescueSource',e.target.value)} placeholder="Street / shelter / owner surrender"/></label><label className="span-2">Photo URL<input value={form.photoUrl||''} onChange={e=>set('photoUrl',e.target.value)} placeholder="https://…"/></label><label className="span-2">Notes<textarea rows={5} value={form.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="Medical or operational notes…"/></label></div>{form.photoUrl&&<div className="photo-preview"><img src={form.photoUrl} alt="Animal preview"/></div>}{error&&<div className="inline-error">{error}</div>}</form>
}

function AnimalProfile({animal,treatments,onEdit}:{animal:Animal;treatments:Treatment[];onEdit:()=>void}){
 const [activeTab,setActiveTab]=useState('Overview')
 return <div className="profile"><section className="profile-hero">{animal.photoUrl?<img className="big-avatar photo" src={animal.photoUrl} alt=""/>:<div className="big-avatar">{animal.name.charAt(0).toUpperCase()}</div>}<div><p className="eyebrow">{animal.animalType} · {animal.animalCode}</p><h2>{animal.name}</h2><p className="muted">{animal.status} · {animal.location||'No location'}</p></div><button className="secondary edit-button" onClick={onEdit}>Edit animal</button></section>
 <nav className="tabs">{['Overview','Medical','Treatments','Vaccines','Deworming','Vet visits','Documents'].map(tab=><button key={tab} className={activeTab===tab?'active':''} onClick={()=>setActiveTab(tab)}>{tab}</button>)}</nav>
 {activeTab==='Overview'&&<section className="profile-grid"><article className="panel"><p className="eyebrow">IDENTITY</p><dl><dt>Animal ID</dt><dd>{animal.animalCode}</dd><dt>Sex</dt><dd>{animal.sex}</dd><dt>Weight</dt><dd>{animal.weightKg?animal.weightKg+' kg':'—'}</dd><dt>Microchip</dt><dd>{animal.microchipNumber||'—'}</dd><dt>Date of birth</dt><dd>{animal.dateOfBirth||'—'}</dd><dt>Intake</dt><dd>{animal.intakeDate}</dd><dt>Rescue source</dt><dd>{animal.rescueSource||'—'}</dd></dl></article><article className="panel"><p className="eyebrow">ACTIVE TREATMENTS</p>{treatments.length===0?<p className="muted">No treatment plans recorded.</p>:<div className="treatment-list">{treatments.map(t=><TreatmentCard key={t.id} animalId={animal.id} treatment={t}/>)}</div>}</article></section>}
 {activeTab==='Treatments'&&<section className="treatment-list full-width">{treatments.length===0?<div className="panel"><p className="muted">No treatment plans recorded.</p></div>:treatments.map(t=><TreatmentCard key={t.id} animalId={animal.id} treatment={t} expanded/>)}</section>}
 {activeTab!=='Overview'&&activeTab!=='Treatments'&&<section className="panel"><p className="eyebrow">{activeTab.toUpperCase()}</p><p className="muted">This module is planned for the next iteration.</p></section>}
 {animal.notes&&activeTab==='Overview'&&<section className="panel notes"><p className="eyebrow">NOTES</p><p>{animal.notes}</p></section>}</div>
}
function TreatmentCard({animalId,treatment,expanded=false}:{animalId:string;treatment:Treatment;expanded?:boolean}){
 const [administrations,setAdministrations]=useState<Administration[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function load(){try{setAdministrations(await getAdministrations(animalId,treatment.id));setError('')}catch{setError('Could not load schedule')}} useEffect(()=>{load()},[animalId,treatment.id])
 async function generate(){setBusy(true);try{await generateAdministrations(animalId,treatment.id,14);await load()}catch(e){setError(e instanceof Error?e.message:'Could not generate schedule')}finally{setBusy(false)}}
 async function act(a:Administration){setBusy(true);try{await administer(animalId,treatment.id,a.id,'');await load()}catch(e){setError(e instanceof Error?e.message:'Could not record administration')}finally{setBusy(false)}}
 async function mark(a:Administration,status:'MISSED'|'SKIPPED'){setBusy(true);try{await setAdministrationStatus(animalId,treatment.id,a.id,status);await load()}catch(e){setError(e instanceof Error?e.message:'Could not update administration')}finally{setBusy(false)}}
 return <div className="treatment"><div className="treatment-head"><div><strong>{treatment.medication}</strong><span>{treatment.dose} · {treatment.route} · {treatment.frequency}</span><small>{treatment.startDate}{treatment.endDate?' → '+treatment.endDate:''}</small></div><button className="secondary small" disabled={busy} onClick={generate}>{busy?'…':'Generate schedule'}</button></div>{error&&<div className="inline-error">{error}</div>}{expanded&&administrations.length>0&&<div className="administrations">{administrations.slice(0,30).map(a=><div className="administration" key={a.id}><div><strong>{new Date(a.scheduledAt).toLocaleString()}</strong><small>{a.status}{a.administeredAt?' · '+new Date(a.administeredAt).toLocaleTimeString()+' · '+a.administeredBy:''}</small></div>{a.status==='SCHEDULED'&&<div className="actions"><button className="primary small" disabled={busy} onClick={()=>act(a)}>ADMINISTER</button><button className="secondary small" disabled={busy} onClick={()=>mark(a,'SKIPPED')}>Skip</button></div>}</div>)}</div>}{!expanded&&administrations.length>0&&<div className="next-dose"><span>Next: {new Date(administrations.find(a=>a.status==='SCHEDULED')?.scheduledAt||administrations[0].scheduledAt).toLocaleString()}</span><span className="chip">{administrations.filter(a=>a.status==='ADMINISTERED').length} administered</span></div>}</div>
}
